spring.application.name=ReliefConnectForum
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
spring.session.store-type=none
spring.profiles.active=dev
